apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend-statefulset
  labels:
    app: backend
spec:
  serviceName: backend-service
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: portfolio-backend:v3
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db-name
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        volumeMounts:
        - name: backend-storage
          mountPath: /app/data
        - name: backend-logs
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: backend-storage
      labels:
        app: backend
        component: storage
    spec:
      accessModes: 
        - "ReadWriteOnce"
      storageClassName: "standard"
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: backend-logs
      labels:
        app: backend
        component: logs
    spec:
      accessModes:
        - "ReadWriteOnce"
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
