apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: portfolio-app
type: Opaque
data:
  # Base64 encoded values (use: echo -n "value" | base64)
  # Default values: username=admin, password=secretpassword
  username: YWRtaW4=
  password: c2VjcmV0cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: portfolio-app
type: Opaque
data:
  # JWT secret for authentication
  jwt-secret: bXlzdXBlcnNlY3JldGp3dGtleWZvcnBvcnRmb2xpbw==
  
  # API keys (base64 encoded)
  api-key: YWJjZGVmZ2hpams=
  
  # Database connection string
  db-connection-string: cG9zdGdyZXM6Ly9hZG1pbjpzZWNyZXRwYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvcG9ydGZvbGlvX2Ri
